[package]
name = "ctftimebot"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[[bin]]
name = "ctftimebot"
doc = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.14"
env_logger = "0.6"
envy = "0.4.0"
lazy_static = "1.3"
log = "0.4"
regex = "1.1.9"
reqwest = "0.9.19"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_with = "1.2.0"
slack-hook = "0.8"

[profile.release]
lto = true
panic = "abort"
