[package]
name = "ctftimebot"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
edition = "2018"

[[bin]]
name = "ctftimebot"
doc = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
env_logger = "0.7"
envy = "0.4.1"
lazy_static = "1.4"
log = "0.4"
regex = "1.4.0"
reqwest = { version = "0.10.8", features = [ "blocking", "json" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_with = "1.5.1"

[profile.release]
lto = true
panic = "abort"
