[package]
name = "ctftimebot"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]

[[bin]]
name = "ctftimebot"
doc = false

[dependencies]
chrono = "0.3"
derive_builder = { version = "0.4", features = ["private_fields"]}
dotenv = "0.10"
envy = "0.3"
lazy_static = "0.2"
reqwest = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slack-hook = "0.4"
xml-rs = "0.4"

# [dependencies.derive_builder]
# version = "0.4"
# features = ["private_fields"]

[profile.release]
lto = true
panic = "abort"