name: Post in Chat
on:
  workflow_dispatch:

jobs:
  post_in_chat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download pre-compiled binary
        run: wget https://github.com/jonasbb/ctftimebot/releases/download/latest/ctftimebot && chmod +x ./ctftimebot
      - name: Post Chat
        run: ./ctftimebot
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
